{{- if and .Values.sanity.enabled .Values.sanity.viewer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sanity-viewer
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: sanity-viewer
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector: {{- include "common.labels.matchLabels" (dict "customLabels" .Values.podLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: sanity-viewer
{{- end }}
