name: Test and coverage (example bank)

on:
  # NOTE: temporarily disabled on the develop branch.
  pull_request:
    branches-ignore:
      - develop
    paths:
      - 'example-bank/**'
      - '.github/workflows/example-bank-test.yml'
  push:
    branches-ignore:
      - develop
    paths:
      - 'example-bank/**'
      - '.github/workflows/example-bank-test.yml'
  workflow_dispatch:

concurrency:
  group: check-example-bank-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: example-bank

jobs:
  test:
    name: test with ${{ matrix.py }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.10"
        os:
          - ubuntu-latest
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: openg2p
          POSTGRES_PASSWORD: openg2p
          POSTGRES_DB: openg2p
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - name: Install test requirements
        run: |
          python -m pip install -r test-requirements.txt
          python -m pip install -e openg2p-example-bank-api
#          TODO: add other packages here
      - name: Run test suite
        run: |
          pytest --cov-branch --cov-report=term-missing --cov=openg2p_example_bank_api --cov=tests openg2p-example-bank-api
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
