name: Publish to PyPI (example bank)

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: example-bank

jobs:
  publish-models:
    name: Publish example-bank-models to PyPI
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: actions/checkout@v3
    - name: Install build dependencies
      run: pip install build
    - name: Build distribution
      run: python -m build ./openg2p-example-bank-models
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages-dir: example-bank/openg2p-example-bank-models/dist/

  publish-api:
    name: Publish example-bank-api to PyPI
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: actions/checkout@v3
    - name: Install build dependencies
      run: pip install build
    - name: Build distribution
      run: python -m build ./openg2p-example-bank-api
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages-dir: example-bank/openg2p-example-bank-api/dist/

  publish-beat-producers:
    name: Publish example-bank-celery-beat-producers to PyPI
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: actions/checkout@v3
    - name: Install build dependencies
      run: pip install build
    - name: Build distribution
      run: python -m build ./openg2p-example-bank-celery-beat-producers
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages-dir: example-bank/openg2p-example-bank-celery-beat-producers/dist/

  publish-workers:
    name: Publish example-bank-celery-workers to PyPI
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: actions/checkout@v3
    - name: Install build dependencies
      run: pip install build
    - name: Build distribution
      run: python -m build ./openg2p-example-bank-celery-workers
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages-dir: example-bank/openg2p-example-bank-celery-workers/dist/
